services:
  webapp-backend:
    restart: always
    depends_on:
      - db
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./service:/app

    command: >
      sh -c "python manage.py migrate --noinput & python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:14.6-alpine
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST=${DB_HOST}
    ports:
      - "5436:${DB_PORT}"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: