# Generated by Django 3.2.25 on 2024-09-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='name',
            field=models.CharField(default='sub_name', max_length=50),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='plan_type',
            field=models.CharField(choices=[('full', 'Full'), ('student', 'Student'), ('discount', 'Discount')], max_length=20),
        ),
    ]
